### PR TITLE
update for Unicode 16.0.0

### PR DESCRIPTION
**Pull request by stevengj**
Draft PR to update our data tables to the upcoming [Unicode 16.0.0 standard](https://www.unicode.org/versions/Unicode16.0.0/).

`data_generator.jl` script is currently failing with:
```
julia --project=. data_generator.jl > utf8proc_data.c.new
ERROR: LoadError: AssertionError: !(haskey(comb_indices, dm1))
Stacktrace:
 [1] top-level scope
   @ ~/Documents/Code/utf8proc/data/data_generator.jl:325
in expression starting at /Users/stevenj/Documents/Code/utf8proc/data/data_generator.jl:293
```
@c42f, since you wrote/ported this script in #258, can you help?

### CODE REVIEW

**Comment by inkydragon** [comment]
An error occurred while processing Character Decomposition Mapping data.
Here, `dm0, dm1` are new characters obtained after a character decomposition.

Assert fails when `dm0 == dm1`.
I tried the old ruby script, and it also fails at the same assert.

https://github.com/JuliaStrings/utf8proc/blob/3de4596fbe28956855df2ecb3c11c0bbc3535838/data/data_generator.jl#L318-L325

In other words, we assume that a character will not be split into two identical characters.

But Unicode 16 introduces a new character: `KIRAT RAI VOWEL SIGN AI (16D68)`.
It will be split into two `KIRAT RAI VOWEL SIGN E (16D67)`.

image
> P683, Figure 13-16
> [The Unicode Standard, Version 16.0 – Core Specification](https://www.unicode.org/versions/Unicode16.0.0/UnicodeStandard-16.0.pdf)

**Comment by stevengj** [comment]
Naively commenting out the assert doesn't work; it fails the normalization test for [U+113C5](https://www.charactercodes.net/113C5), which is another such character introduced in Unicode 16.0 that decomposes into two identical characters [U+113C2)](https://www.charactercodes.net/113C2) + U+113C2.

**Comment by eschnett** [comment]
Do we also need to introduce re-combining? If we start with [16D67, 16D68, 16D67], should this then result in [16D68, 16D68]?

**Comment by eschnett** [comment]
If I understand the combining table correctly, then bit 15 (`0x8000`) indicates whether a character can be the left character (bit is zero) or the right character (bit is one) in a combining pair. This would make it impossible to combine two identical characters.

If I understand correctly, then bit 14 (`0x4000`) indicates whether the result can be stored in 16 bits or requires 32 bits.

If that is correct, then the following approach would work:
- Don't use bit 14. Instead, use bit 15 of the combined character to indicate whether there is a continuation character. This essentially stores the result as utf16.
- Split bit 15 into two bits, "can be the left character" and "can be the right character".

This change would not change the logic much, and there would not need to be a new table.

**Comment by eschnett** [comment]
Nope, this wouldn't work. The combining table is used for two different purposes. For the first combining character it stores an index pointing to a second table, and for the second combining table it stores an index into that second table.

See https://github.com/JuliaStrings/utf8proc/pull/277 for a redesign. The combining table is quite small (less than 1000 characters overall), and for each first character even smaller (16 (?) second characters at most). I'm storing the secondary table as array and iterate through it.

**Comment by stevengj** [comment]
@inkydragon, let's stick with @eschnett's approach for now, just to get support for Unicode 16 out the door.

In the future, it would be nice to benchmark alternative approaches, though.

**Comment by eschnett** [comment]
I thought about benchmarking... The question is, what cases do you want to benchmark? Long strings or short ones? Mostly ASCII or other characters? Where is this used in Julia? And if we're optimizing memory allocations and loops and table lookups: Why stick with C? So, no benchmarking now...

**Comment by stevengj** [comment]
I suspect that normalization is mainly used for relatively short strings, though in that case the performance in Julia may be dominated by memory-allocation overhead. 

I would tend to benchmark with relatively long strings, to amortize the overhead, and mostly ASCII strings (since I suspect that this is the common case for string processing, even in international contexts).

**Pull request closed without merging**
