### PR TITLE
Fix Sign-Conversion warnings in library and test code

### PR DESCRIPTION
**Pull request by mike-glorioso**
Added explicit casts or changed variable types to remove Sign-Conversion warnings from utf8proc.c
Turned on Sign-Conversion warnings in Makefile
Changes to tests will be coming in a separate PR

### CODE REVIEW

**Comment by stevengj** [comment]
LGTM, thanks.

**Comment by stevengj** [comment]
Is this ready to merge or do you have more fixes pending?

**Comment by mike-glorioso** [comment]
@stevengj This is now ready to merge and should resolve #169

**Comment by stevengj** [comment]
LGTM.

**Pull request merged**
